const BASE_URL = "http://localhost:3000";

const USER_REGISTRATION_API_URL = `${BASE_URL}/signup`;
const USER_LOGIN_API_URL = `${BASE_URL}/login`;
const USER_LOGOUT_API_URL = `${BASE_URL}/logout`;

const ALL_PRODUCT_API_URL = `${BASE_URL}/products`;
const GET_PRODUCT_BY_ID_API_URL = `${BASE_URL}/products/:id`;
const CREATE_PRODUCT_API_URL = `${BASE_URL}/products`;
const UPDATE_PRODUCT_API_URL = `${BASE_URL}/products/:id`;
const DELETE_PRODUCT_API_URL = `${BASE_URL}/products/:id`;
const SEARCH_PRODUCTS_API_URL = `${BASE_URL}/products/search`;

const ALL_CATEGORIES_API_URL = `${BASE_URL}/categories`;
const CREATE_CATEGORY_API_URL = `${BASE_URL}/categories`;
const UPDATE_CATEGORY_API_URL = `${BASE_URL}/categories/:id`;
const DELETE_CATEGORY_API_URL = `${BASE_URL}/categories/:id`;

const GET_PRODUCTS_BY_IDS_API_URL = `${BASE_URL}/products/by-ids`;
const GET_USER_CART_API_URL = `${BASE_URL}/cart`;
const ADD_TO_CART_API_URL = `${BASE_URL}/cart_items`;
const UPDATE_CART_ITEM_API_URL = `${BASE_URL}/cart_items/:id`;
const DELETE_CART_ITEM_API_URL = `${BASE_URL}/cart_items/:id`;
const MERGE_CART_API_URL = `${BASE_URL}/cart`;

export {
  USER_REGISTRATION_API_URL,
  USER_LOGIN_API_URL,
  USER_LOGOUT_API_URL,
  ALL_PRODUCT_API_URL,
  GET_PRODUCT_BY_ID_API_URL,
  CREATE_PRODUCT_API_URL,
  ALL_CATEGORIES_API_URL,
  CREATE_CATEGORY_API_URL,
  UPDATE_CATEGORY_API_URL,
  DELETE_CATEGORY_API_URL,
  SEARCH_PRODUCTS_API_URL,
  UPDATE_PRODUCT_API_URL,
  DELETE_PRODUCT_API_URL,
  GET_PRODUCTS_BY_IDS_API_URL,
  GET_USER_CART_API_URL,
  ADD_TO_CART_API_URL,
  UPDATE_CART_ITEM_API_URL,
  DELETE_CART_ITEM_API_URL,
  MERGE_CART_API_URL,
};
